name: Hourly build
on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch: {}
jobs:
    build:
        name: Build and publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/cache@v2
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: Install packages
              run: yarn install

            - name: Build
              run: yarn build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_dir: ./public
                  cname: blahaj.quest
